### ISSUE TITLE
how to use it on mac

### ISSUE THREAD

**Issue by lhjandroid** [tekartik/process_run.dart#11]
i have use this plug on flutter,but i use it whit this shell
`/Users/lihongjun/shell/libs/zipalign -v 4 "/Users/lihongjun/Downloads/test-signed-20200615181849.apk" "/Users/lihongjun/Documents/test/tempApk/test-signed-20200615181849_aligned.apk
 Shell shell = Shell(runInShell: false,);
    shell.run(shell).then((value){
      print(value);
    });
`
it just an zipalign shell int macos app
and the result is
`workingDirectory: /Users/lihongjun/Library/Containers/io.flutter.macostestbed/Data

Missing working directory /Users/lihongjun/Library/Containers/io.flutter.macostestbed/Data

[ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: ShellException(ProcessException: Operation not permitted
  Command: /Users/lihongjun/shell/libs/zipalign -v 4 /Users/lihongjun/Downloads/test-signed-20200615181849.apk /Users/lihongjun/Documents/test/tempApk/test-signed-20200615181849_aligned.apk)
#0      Shell.run (package:process_run/shell.dart:267:9)`
need help thanks

**Comment by alextekartik** [comment]
I'm not sure but in the MacOS flutter context, I think you need to disable the sandbox mode.

See https://stackoverflow.com/questions/7018354/remove-sandboxing and https://github.com/tekartik/process_run.dart/issues/3

I think I need to document that (so far I never tested that in a flutter context).

**Comment by webskydavid** [comment]
Hi, have the same issue. Try to run the example script but become this warning:
```
$ echo Hello
Hello
$ dart --version
Dart VM version: 2.9.0-19.0.dev.flutter-7e72c9ae7e (be) (Fri Jun 19 18:05:23 2020 +0000) on "macos_x64"
$ flutter pub --version
Flutter 1.20.0-2.0.pre • channel dev • https://github.com/flutter/flutter.git
Framework • revision 15a28159bc (10 days ago) • 2020-06-23 04:52:58 -0700
Engine • revision 91a63d6a44
Tools • Dart 2.9.0 (build 2.9.0-19.0.dev 7e72c9ae7e)
$ cd /Users/-----------/development/work/kup_app/example
$ dir
ProcessException: No such file or directory
  Command: dir
$ dir
workingDirectory: /Users/------------/development/work/kup_app/example
Missing working directory /Users/----------/development/work/kup_app/example
[ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: ShellException(dir, error: ProcessException: No such file or directory
  Command: dir , workingDirectory: /Users/------------/development/work/kup_app/example)
#0      Shell.run 
package:process_run/shell.dart:282
<asynchronous suspension>
#1      _MainPageState.build.<anonymous closure> 
package:kup_app/main.dart:150
<asynchronous suspension>
#2      _MainPageState.build.<anonymous closure> (package:kup_app/main.dart)
#3      _InkResponseState._handleTap 
package:flutter/…/material/ink_well.dart:992
#4      _InkResponseState.build.<anonymous closure> 
package:flutter/…/material/ink_well.dart:1098
#5      GestureRecognizer.invokeCallback 
package:flutter/…/gestures/recognizer.dart:184
#6      TapGestureRecognizer.handleTapUp 
package:flutter/…/gestures/tap.dart:524
#7      BaseTapGestureRecognizer._checkUp 
package:flutter/…/gestures/tap.dart:284
#8      BaseTapGestureRecognizer.handlePrimaryPointer 
package:flutter/…/gestures/tap.dart:219
#9      PrimaryPointerGestureRecognizer.handleEvent 
package:flutter/…/gestures/recognizer.dart:477
#10     PointerRouter._dispatch 
package:flutter/…/gestures/pointer_router.dart:78
#11     PointerRouter._dispatchEventToRoutes.<anonymous closure> 
package:flutter/…/gestures/pointer_router.dart:124
#12     _LinkedHashMapMixin.forEach  (dart:collection-patch/compact_hash.dart:377:8)
#13     PointerRouter._dispatchEventToRoutes 
package:flutter/…/gestures/pointer_router.dart:122
#14     PointerRouter.route 
package:flutter/…/gestures/pointer_router.dart:108
#15     GestureBinding.handleEvent 
package:flutter/…/gestures/binding.dart:220
#16     GestureBinding.dispatchEvent 
package:flutter/…/gestures/binding.dart:200
#17     GestureBinding._handlePointerEvent 
package:flutter/…/gestures/binding.dart:158
#18     GestureBinding._flushPointerEventQueue 
package:flutter/…/gestures/binding.dart:104
#19     GestureBinding._handlePointerDataPacket 
package:flutter/…/gestures/binding.dart:88
#20     _rootRunUnary  (dart:async/zone.dart:1206:13)
#21     _CustomZone.runUnary  (dart:async/zone.dart:1100:19)
#22     _CustomZone.runUnaryGuarded  (dart:async/zone.dart:1005:7)
#23     _invoke1  (dart:ui/hooks.dart:283:10)
#24     _dispatchPointerDataPacket  (dart:ui/hooks.dart:192:5)
```

I added also paths in the `/Users/-------/.config/tekartik/process_run/env.yaml` 
Sandboxing turned off.
```
# Local Environment path and variable for `Shell.run` calls.
#
# `path(s)` is a list of path, `var(s)` is a key/value map.
#
# Content example. See <https://github.com/tekartik/process_run.dart/blob/master/doc/user_config.md> for more information
#
path:
  - ./local
  - bin/
# var:
#   MY_PWD: my_password
#   MY_USER: my user
```

Here is the code:
```
var s = shell.Shell();
var userPaths = getUserPaths(<String, String>{});
await s.run('''
 # Display some text
echo Hello
# Display dart version
dart --version
# Display pub version
 flutter pub --version
''');

s = s.pushd('example');
await s.run('''
# Listing directory in the example folder
dir
 ''');
s = s.popd();
```
What I want to achieve is to run some .sh scripts from files after building the app.

**Comment by webskydavid** [comment]
@lhjandroid I think your working directory where you run the shell needs to be this directory where you have the zipalign. If I want to run shell script I need to change the working directory for example:
`var s = shell.Shell(workingDirectory: '$path/${VALUES.kupScriptDirectory}');`

For me it works fine if I write the script directly to the run() method. But if I try to use a script file like `./main.sh` it tells me that I have no permissions:
```
/bin/sh: ./main.sh: Permission denied
[ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: ShellException(./main.sh /Users/-----/development/work 2020-06-01 2020-06-30, exitCode 126, workingDirectory: /Users/-----/Library/Application Support/com.example.kupApp/kup-script)
```

**Comment by alextekartik** [comment]
I'm not sure `dir` is a supported macos command. Some things I could think of:
- Can you check it works on a terminal (zsh)? You can try `ls -l` instead of dir.
- also make sure you `main.sh` is marked as executable (`chmod +x main.sh`).
- Also can you confirm that the directory/file does exist?

**Comment by webskydavid** [comment]
I found a solution. After downloading files from GITHUB and extracting the zip file there was no permission for running these scripts. I added for each file`chmod 755` after extracting.

**Comment by lhjandroid** [comment]
> I found a solution. After downloading files from GITHUB and extracting the zip file there was no permission for running these scripts. I added for each filechmod 755 after extracting.

finaly i move the sanBox，see the See https://stackoverflow.com/questions/7018354/remove-sandboxing and #3 you should sign the commline files. becaus the macOs App just for me. so i just remove the sanBox setting

**Comment by dupengtao** [comment]
remove
	<key>com.apple.security.app-sandbox</key>
	<true/>
