### ISSUE TITLE
ProcesException: Permissino denied

### ISSUE THREAD

**Issue by glennmichaelmejias** [tekartik/process_run.dart#21]
i want to install and able to run git on my flutter app.

Unhandled Exception: ShellException(git, error: ProcessException: Permission denied
E/flutter ( 1432):   Command: git , workingDirectory: /)
E/flutter ( 1432): #0      Shell.runExecutableArguments (package:process_run/shell.dart:297:7)

**Comment by alextekartik** [comment]
Thanks for the report. Can you specify on which platform you are ([MacOS requires some xcode setting](https://github.com/tekartik/process_run.dart/blob/12133dcd54a24a2b0abc4cd5faf824c57231e187/README.md#macos) to allow spawning binaries) to see how I can reproduce the issus?
This simple test works for me (event run inside a flutter app:

```dart
import 'package:process_run/shell.dart';

Future main() async {
  var shell = Shell();
  await shell.run('git --version');
}
```

Make sure you using the latest version of process_run. It seems you are using `/` as the working directory which could be the issue too.

**Comment by glennmichaelmejias** [comment]
@alextekartik thanks for reply. how to change working directory?

**Comment by alextekartik** [comment]
There is a working directory argument in Shell.

```dart
// Specify a directory
var shell = Shell(workingDirectory: '/home');

// Change directory
shell = shell.cd('/other_dir');
```

**Comment by glennmichaelmejias** [comment]
here is my full code

`
import 'package:process_run/shell.dart';

import 'package:flutter/material.dart';

class TerminalWindow extends StatefulWidget {
  @override
  _TerminalWindowState createState() => _TerminalWindowState();
}

class _TerminalWindowState extends State<TerminalWindow> {


  @override
  void initState() {
    // TODO: implement initState
   
    super.initState();
     
  }

  void onInput(String input) {
    print('input: $input');
   
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.blueGrey,
     
      floatingActionButton: FloatingActionButton(
        onPressed: (){
         
         testing();
          
        },
      ),
    );
  }
}



void testing()async{
 var shell = Shell(workingDirectory: "/home");
  await shell.run('git --version');
}
`



when i try to run it says

`
 [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: ShellException(git --version, error: ProcessException: No such file or directory
E/flutter (10839):   Command: git --version, workingDirectory: /home)
E/flutter (10839): #0      Shell.runExecutableArguments (package:process_run/shell.dart:297:7)
`

**Comment by alextekartik** [comment]
Some questions:
* Again Can you specify on which platform you are ? 
* Is git in your path when running the application ? (you can `print(await which('git'))`)
* Does the folder '/home' exists ? 
* Which version of process_run are you using? (please use latest)
* Does it work in a regular dart program like I write above

**Comment by glennmichaelmejias** [comment]
- i am using android
- when i try print(await which('git')); it says null
- i don't know, where should i put working directory should i put it on my assets folder in flutter project?
- i am using process_run: ^0.10.12+2
- it can work with echo

**Comment by alextekartik** [comment]
> i am using android

Ok that's the reason, there is no git client on Android

> i don't know, where should i put working directory

Use path_provider to get a correct location

**Comment by glennmichaelmejias** [comment]
okay thank you. can i use apt get install git? i want to create a window similar to termux

**Comment by alextekartik** [comment]
> can i use apt get install git?

I don't think so. Although android based on Linux I don't think you have access to any debian install tool

**Comment by glennmichaelmejias** [comment]
what if i will put the executables on the directory that i can access? and run it with ./git
is it possible?

**Comment by alextekartik** [comment]
> what if i will put the executables on the directory that i can access? and run it with ./git
> is it possible?

Yes.

**Comment by glennmichaelmejias** [comment]
okay thank you so much. i will try.

**Comment by arzakmiftakhul** [comment]
How about this issue? I can run some scripts just using `await shell.run()` on Lineage OS for raspberry pi 4 (konstakang) without working directory setting. But I can't use it on Android 9 for Radxa Zero. It always show the error 
```
E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: ShellException(dart --version, error: ProcessException: Permission denied
      Command: dart --version, workingDirectory: /)
```
Which working directory should it be? Even just run simple script `await shell.run("ls")`, I got same error.

**Comment by alextekartik** [comment]
I'm don't think you can run any system command on Android for security reason. You might be able to bundle an executable then extract it in a folder you have write access to (use `path_provider` to find the location) and run it from here. However this package mainly target Desktop (as mentioned in the README.md) and I never tested on mobile yet.

**Comment by arzakmiftakhul** [comment]
> I'm don't think you can run any system command on Android for security reason. You might be able to bundle an executable then extract it in a folder you have write access to (use `path_provider` to find the location) and run it from here. However this package mainly target Desktop (as mentioned in the README.md) and I never tested on mobile yet.

Thanks for this great library. I've installed Lineage OS android 11 on raspberry 4 from [Konstakang](https://konstakang.com/devices/rpi4/LineageOS18/). I can run system command for example copy/move file from Document folder to connected flash disk, check device temperature, reboot device, etc. But I get an error when I run on [Radxa Zero](https://wiki.radxa.com/Zero) device. Both were rooted devices.

**Comment by Sendhavshab** [comment]
> > I'm don't think you can run any system command on Android for security reason. You might be able to bundle an executable then extract it in a folder you have write access to (use `path_provider` to find the location) and run it from here. However this package mainly target Desktop (as mentioned in the README.md) and I never tested on mobile yet.
> 
> Thanks for this great library. I've installed Lineage OS android 11 on raspberry 4 from [Konstakang](https://konstakang.com/devices/rpi4/LineageOS18/). I can run system command for example copy/move file from Document folder to connected flash disk, check device temperature, reboot device, etc. But I get an error when I run on [Radxa Zero](https://wiki.radxa.com/Zero) device. Both were rooted devices.



can you give  me example how to reboot device i am trying and i got this error 

`
ShellException (ShellException(adb shell reboot, error: ProcessException: Permission denied
  Command: adb shell reboot, workingDirectory: /data/user/0/com.example.test/app_flutter))
`

`
   final path = await getApplicationDocumentsDirectory();

    var shell = Shell(workingDirectory: path.path);

    await shell.run('adb shell reboot');
`
