### ISSUE TITLE
How to use onProcess?

### ISSUE THREAD

**Issue by git-boya** [tekartik/process_run.dart#89]
I want to monitor the real-time progress of ffmpeg:
example:
``` dart
 static Future test(String inputFile, String outFile) async{
    var shell = Shell(
      stdoutEncoding: const Utf8Codec(),
      stderrEncoding: const Utf8Codec(),
    );
    ProcessResult result =
    await shell.runExecutableArguments("ffmpeg", ["-i", inputFile, outFile], onProcess: (process){
      process.stdout.transform(const Utf8Decoder()).listen((data) {
        print("INFO $data");
      });
    });
  }
```
Error reported in this code:
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Bad state: Stream has already been listened to.
#0      _StreamController._subscribe (dart:async/stream_controller.dart:676:7)
#1      _ControllerStream._createSubscription (dart:async/stream_controller.dart:827:19)
#2      _StreamImpl.listen (dart:async/stream_impl.dart:471:9)
#3      _Socket.listen (dart:io-patch/socket_patch.dart:2214:31)
#4      _StdStream.listen (dart:io/stdio.dart:22:20)
#5      runExecutableArguments (package:process_run/src/process_run.dart:144:18)
<asynchronous suspension>
#6      processCmdRun (package:process_run/src/process_run.dart:220:12)
<asynchronous suspension>
#7      Shell._lockedRunExecutableArguments.run (package:process_run/src/shell.dart:411:29)
<asynchronous suspension>
```

How do I apply?

thanks!

**Comment by alextekartik** [comment]
`onProcess` only gives you basic information about the process. The solution is to setup a controller on the output of the Shell to capture what ffmgep write. There is a basic `ShellLinesController` that allow to easily receive (and parse or filter) output lines of text that could be use the following way (ffmeg writes mostly on the output, here I capture only some lines):


```dart
static Future test(String inputFile, String outFile) async {
  // Create output controller and filter out output lines
  var controller = ShellLinesController();
  controller.stream.listen((line) {
    // Only display some lines
    line = line.trim().toLowerCase();
    if (line.startsWith('input #') ||
        line.startsWith('stream #') ||
        line.startsWith('frame=')) {
      print(line);
    }
  });
  // set controller on the stderr.
  var shell = Shell(stderr: controller.sink);
  // Run
  await shell.runExecutableArguments("ffmpeg", ["-i", inputFile, outFile]);
}
```

**Comment by git-boya** [comment]
@alextekartik thank you
